<?php
declare(strict_types=1);
namespace App\Services;
use PDO;use RuntimeException;
final class PosService
{
    public function __construct(private PDO$pdo){}
    public function mutate(array$actor,array$payload):array
    {
        $action=(string)($payload['action']??'');$key=(string)($payload['key']??'');if(!preg_match('/^[a-f0-9-]{36}$/i',$key))throw new RuntimeException('VALIDATION_ERROR');
        $this->pdo->beginTransaction();
        try{$insert=$this->pdo->prepare('INSERT IGNORE INTO pos_mutation_requests(actor_id,request_key,payload) VALUES(?,?,?)');$encoded=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$insert->execute([$actor['id'],$key,$encoded]);$s=$this->pdo->prepare('SELECT payload,result FROM pos_mutation_requests WHERE actor_id=? AND request_key=? FOR UPDATE');$s->execute([$actor['id'],$key]);$previous=$s->fetch();if($this->canonical(json_decode($previous['payload'],true))!==$this->canonical($payload))throw new RuntimeException('IDEMPOTENCY_CONFLICT');if($previous['result']){$this->pdo->commit();return json_decode($previous['result'],true);}
            if(!in_array($action,['save_draft','confirm_order','delete_draft'],true)&&$actor['role']!=='admin')throw new RuntimeException('FORBIDDEN');
            $result=match($action){
                'save_draft'=>$this->saveDraft($actor,$payload),
                'confirm_order'=>$this->orderAction($actor,$payload,'confirm'),
                'delete_draft'=>$this->orderAction($actor,$payload,'delete'),
                'cancel_order'=>$this->orderAction($actor,$payload,'cancel'),
                'return_order'=>$this->returnOrder($actor,$payload),
                'product'=>$this->saveProduct($actor,$payload),
                'inventory'=>$this->inventory($actor,$payload),
                'exchange'=>$this->exchange($actor,$payload),
                'glass_brand'=>$this->glassBrand($actor,$payload),
                'staff_state'=>$this->staffState($actor,$payload),
                default=>throw new RuntimeException('VALIDATION_ERROR'),
            };
            $this->audit($actor['id'],$action,(string)($result['id']??''));$this->pdo->prepare('UPDATE pos_mutation_requests SET result=? WHERE actor_id=? AND request_key=?')->execute([json_encode($result),$actor['id'],$key]);$this->pdo->commit();return$result;
        }catch(\Throwable$error){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$error;}
    }
    public function deleteProduct(array$actor,array$payload):array
    {
        if($actor['role']!=='admin')throw new RuntimeException('FORBIDDEN');$id=(string)($payload['id']??'');$version=(int)($payload['version']??0);$this->pdo->beginTransaction();try{$p=$this->one('SELECT p.*,b.on_hand FROM pos_products p JOIN pos_inventory_balances b ON b.product_id=p.id WHERE p.id=? AND p.deleted_at IS NULL FOR UPDATE',[$id]);if(!$p)throw new RuntimeException('PRODUCT_NOT_FOUND');if((int)$p['version']!==$version)throw new RuntimeException('VERSION_CONFLICT');if((int)$p['on_hand']!==0)throw new RuntimeException('PRODUCT_HAS_STOCK');$s=$this->pdo->prepare("SELECT 1 FROM pos_sales_order_items i JOIN pos_sales_orders o ON o.id=i.order_id WHERE i.product_id=? AND o.status='draft' LIMIT 1");$s->execute([$id]);if($s->fetchColumn())throw new RuntimeException('PRODUCT_IN_USE');$this->pdo->prepare('UPDATE pos_products SET active=0,deleted_at=NOW(),version=version+1 WHERE id=?')->execute([$id]);$this->audit($actor['id'],'product.delete',$p['sku']);$this->pdo->commit();return['id'=>$id];}catch(\Throwable$error){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$error;}
    }
    private function saveDraft(array$actor,array$p):array
    {
        $items=$p['items']??[];if(!is_array($items)||count($items)<1||count($items)>100)throw new RuntimeException('VALIDATION_ERROR');$id=$p['id']??null;
        if($id){$order=$this->one('SELECT * FROM pos_sales_orders WHERE id=? FOR UPDATE',[$id]);if(!$order||($order['created_by']!==$actor['id']&&$actor['role']!=='admin'))throw new RuntimeException('FORBIDDEN');if($order['status']!=='draft')throw new RuntimeException('INVALID_ORDER_STATE');if((int)$order['version']!==(int)($p['version']??0))throw new RuntimeException('VERSION_CONFLICT');}else{$id=self::uuid();$this->pdo->prepare('INSERT INTO pos_sales_orders(id,created_by) VALUES(?,?)')->execute([$id,$actor['id']]);}
        $seen=[];foreach($items as$item){$pid=(string)($item['product_id']??'');$quantity=(int)($item['quantity']??0);if(isset($seen[$pid])||$quantity<1||$quantity>1000000)throw new RuntimeException('VALIDATION_ERROR');$seen[$pid]=true;$product=$this->one('SELECT * FROM pos_products WHERE id=? AND deleted_at IS NULL FOR SHARE',[$pid]);if(!$product||!$product['active'])throw new RuntimeException('PRODUCT_INACTIVE');$custom=isset($item['custom_name'])?trim((string)$item['custom_name']):null;if($custom==='')$custom=null;$line=$this->one('SELECT id,custom_name FROM pos_sales_order_items WHERE order_id=? AND product_id=?',[$id,$pid]);if($line){$this->pdo->prepare('UPDATE pos_sales_order_items SET quantity=?,custom_name=?,unit_sale_price=?,quoted_price_version=? WHERE id=?')->execute([$quantity,$custom,$product['sale_price'],$product['price_version'],$line['id']]);}else{$this->pdo->prepare('INSERT INTO pos_sales_order_items(id,order_id,product_id,quantity,custom_name,unit_sale_price,quoted_price_version) VALUES(?,?,?,?,?,?,?)')->execute([self::uuid(),$id,$pid,$quantity,$custom,$product['sale_price'],$product['price_version']]);}}
        $placeholders=implode(',',array_fill(0,count($seen),'?'));$this->pdo->prepare("DELETE FROM pos_sales_order_items WHERE order_id=? AND product_id NOT IN({$placeholders})")->execute([$id,...array_keys($seen)]);$s=$this->pdo->prepare('SELECT COALESCE(SUM(quantity*unit_sale_price),0) FROM pos_sales_order_items WHERE order_id=?');$s->execute([$id]);$total=$s->fetchColumn();$this->pdo->prepare('UPDATE pos_sales_orders SET customer_name=?,customer_phone=?,note=?,total_amount=?,version=version+1 WHERE id=?')->execute([trim((string)($p['customer_name']??'')),trim((string)($p['customer_phone']??'')),trim((string)($p['note']??'')),$total,$id]);return['id'=>$id];
    }
    private function orderAction(array$actor,array$p,string$kind):array
    {
        $id=(string)($p['id']??'');$order=$this->one('SELECT * FROM pos_sales_orders WHERE id=? FOR UPDATE',[$id]);if(!$order||($order['created_by']!==$actor['id']&&$actor['role']!=='admin'))throw new RuntimeException('FORBIDDEN');if(in_array($kind,['confirm','delete'],true)){if($order['status']!=='draft')throw new RuntimeException('INVALID_ORDER_STATE');if((int)$order['version']!==(int)($p['version']??0))throw new RuntimeException('VERSION_CONFLICT');}
        if($kind==='delete'){$this->pdo->prepare("UPDATE pos_sales_orders SET status='deleted',exchange_return_id=NULL,version=version+1 WHERE id=?")->execute([$id]);return['id'=>$id];}
        $items=$this->all('SELECT * FROM pos_sales_order_items WHERE order_id=? ORDER BY product_id FOR UPDATE',[$id]);
        if($kind==='confirm'){if(!$items||!in_array($p['payment_method']??'',['cash','transfer'],true))throw new RuntimeException('VALIDATION_ERROR');foreach($items as$item){$product=$this->one('SELECT * FROM pos_products WHERE id=? FOR SHARE',[$item['product_id']]);if(!$product||!$product['active'])throw new RuntimeException('PRODUCT_INACTIVE');if((int)$product['price_version']!==(int)$item['quoted_price_version'])throw new RuntimeException('PRICE_CHANGED');$cost=$this->one('SELECT fixed_cost FROM pos_product_costs WHERE product_id=? FOR SHARE',[$product['id']]);$this->moveStock($product['id'],-(int)$item['quantity'],'sale',$actor['id'],null,$item['id'],null);$this->pdo->prepare('UPDATE pos_sales_order_items SET sku_snapshot=?,product_name_snapshot=COALESCE(custom_name,?),unit_sale_price=? WHERE id=?')->execute([$product['sku'],$product['name'],$product['sale_price'],$item['id']]);$this->pdo->prepare('INSERT INTO pos_sales_item_costs(order_item_id,unit_cost_snapshot) VALUES(?,?)')->execute([$item['id'],$cost['fixed_cost']]);}$this->pdo->prepare("UPDATE pos_sales_orders SET status='confirmed',confirmed_by=?,confirmed_at=NOW(),payment_method=?,version=version+1 WHERE id=?")->execute([$actor['id'],$p['payment_method'],$id]);return['id'=>$id];}
        if($order['status']!=='confirmed'||$this->one('SELECT id FROM pos_sales_returns WHERE order_id=? LIMIT 1',[$id]))throw new RuntimeException('INVALID_ORDER_STATE');$reason=trim((string)($p['reason']??''));if($reason===''||mb_strlen($reason)>1000||!in_array($p['refund_method']??'',['cash','transfer'],true))throw new RuntimeException('VALIDATION_ERROR');foreach($items as$item)$this->moveStock($item['product_id'],(int)$item['quantity'],'cancel',$actor['id'],null,$item['id'],null);$this->pdo->prepare("UPDATE pos_sales_orders SET status='cancelled',cancelled_at=NOW(),cancel_reason=?,cancel_refund_method=?,version=version+1 WHERE id=?")->execute([$reason,$p['refund_method'],$id]);return['id'=>$id];
    }
    private function returnOrder(array$actor,array$p):array
    {
        $id=(string)($p['id']??'');$order=$this->one('SELECT * FROM pos_sales_orders WHERE id=? FOR UPDATE',[$id]);if(!$order||!in_array($order['status'],['confirmed','partially_returned'],true))throw new RuntimeException('INVALID_ORDER_STATE');$items=$p['items']??[];$reason=trim((string)($p['reason']??''));if(!is_array($items)||!$items||count($items)>100||$reason===''||!in_array($p['refund_method']??'',['cash','transfer'],true))throw new RuntimeException('VALIDATION_ERROR');$returnId=self::uuid();$this->pdo->prepare('INSERT INTO pos_sales_returns(id,order_id,reason,refund_method,created_by) VALUES(?,?,?,?,?)')->execute([$returnId,$id,$reason,$p['refund_method'],$actor['id']]);foreach($items as$item){$line=$this->one('SELECT * FROM pos_sales_order_items WHERE id=? AND order_id=? FOR UPDATE',[(string)($item['order_item_id']??''),$id]);if(!$line)throw new RuntimeException('VALIDATION_ERROR');$quantity=(int)($item['quantity']??0);$restock=(int)($item['restock_quantity']??0);if($quantity<1||$restock<0||$restock>$quantity)throw new RuntimeException('VALIDATION_ERROR');$s=$this->pdo->prepare('SELECT COALESCE(SUM(quantity),0) FROM pos_sales_return_items WHERE order_item_id=?');$s->execute([$line['id']]);if($quantity+(int)$s->fetchColumn()>(int)$line['quantity'])throw new RuntimeException('RETURN_EXCEEDS_SOLD');$returnItem=self::uuid();$this->pdo->prepare('INSERT INTO pos_sales_return_items(id,return_id,order_item_id,quantity,restock_quantity,refund_amount) VALUES(?,?,?,?,?,? * ?)')->execute([$returnItem,$returnId,$line['id'],$quantity,$restock,$quantity,$line['unit_sale_price']]);if($restock)$this->moveStock($line['product_id'],$restock,'return',$actor['id'],null,null,$returnItem);}$s=$this->pdo->prepare('SELECT COALESCE(SUM(refund_amount),0) FROM pos_sales_return_items WHERE return_id=?');$s->execute([$returnId]);$refund=$s->fetchColumn();$this->pdo->prepare('UPDATE pos_sales_returns SET refund_amount=? WHERE id=?')->execute([$refund,$returnId]);$sold=$this->scalar('SELECT COALESCE(SUM(quantity),0) FROM pos_sales_order_items WHERE order_id=?',[$id]);$returned=$this->scalar('SELECT COALESCE(SUM(i.quantity),0) FROM pos_sales_return_items i JOIN pos_sales_returns r ON r.id=i.return_id WHERE r.order_id=?',[$id]);$status=(int)$sold===(int)$returned?'returned':'partially_returned';$this->pdo->prepare('UPDATE pos_sales_orders SET status=?,version=version+1 WHERE id=?')->execute([$status,$id]);return['id'=>$id,'return_id'=>$returnId];
    }
    private function saveProduct(array$actor,array$p):array
    {
        $sku=mb_strtoupper(trim((string)($p['sku']??'')),'UTF-8');$name=trim((string)($p['name']??''));$sale=(string)($p['sale_price']??'');$cost=(string)($p['fixed_cost']??'');if($sku===''||mb_strlen($sku)>50||$name===''||mb_strlen($name)>200||!preg_match('/^[0-9]{1,15}$/',$sale)||!preg_match('/^[0-9]{1,15}$/',$cost)||!in_array($p['glass_type']??'',['clear','privacy','matte','other'],true))throw new RuntimeException('VALIDATION_ERROR');$id=$p['id']??null;$models=array_values(array_unique(array_filter(array_map('trim',is_array($p['models']??null)?$p['models']:[]))));
        if(!$id){$id=self::uuid();$this->pdo->prepare('INSERT INTO pos_products(id,sku,name,glass_type,models,brand,glass_brand_id,image_path,sale_price,active) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$id,$sku,$name,$p['glass_type'],json_encode($models,JSON_UNESCAPED_UNICODE),trim((string)($p['brand']??'other')),$p['glass_brand_id']?:null,$p['image_path']??null,$sale,(int)!empty($p['active'])]);$this->pdo->prepare('INSERT INTO pos_product_costs(product_id,fixed_cost) VALUES(?,?)')->execute([$id,$cost]);$this->pdo->prepare('INSERT INTO pos_inventory_balances(product_id) VALUES(?)')->execute([$id]);return['id'=>$id];}
        $product=$this->one('SELECT * FROM pos_products WHERE id=? FOR UPDATE',[$id]);if(!$product||(int)$product['version']!==(int)($p['version']??0))throw new RuntimeException('VERSION_CONFLICT');if($product['sku']!==$sku&&($this->one('SELECT id FROM pos_inventory_movements WHERE product_id=? LIMIT 1',[$id])||$this->one('SELECT id FROM pos_sales_order_items WHERE product_id=? LIMIT 1',[$id])))throw new RuntimeException('SKU_IMMUTABLE');$priceChanged=$product['sale_price']!==$sale?1:0;$this->pdo->prepare('UPDATE pos_products SET sku=?,name=?,glass_type=?,models=?,brand=?,glass_brand_id=?,image_path=?,sale_price=?,price_version=price_version+?,active=?,version=version+1 WHERE id=?')->execute([$sku,$name,$p['glass_type'],json_encode($models,JSON_UNESCAPED_UNICODE),trim((string)($p['brand']??'other')),$p['glass_brand_id']?:null,$p['image_path']??null,$sale,$priceChanged,(int)!empty($p['active']),$id]);$this->pdo->prepare('UPDATE pos_product_costs SET fixed_cost=? WHERE product_id=?')->execute([$cost,$id]);return['id'=>$id];
    }
    private function inventory(array$actor,array$p):array
    {
        $type=(string)($p['type']??'');$reason=trim((string)($p['reason']??''));$items=$p['items']??[];if(!in_array($type,['opening','receipt','issue','damage','adjustment'],true)||$reason===''||mb_strlen($reason)>1000||!is_array($items)||!$items||count($items)>100)throw new RuntimeException('VALIDATION_ERROR');$documentId=self::uuid();$this->pdo->prepare('INSERT INTO pos_inventory_documents(id,type,reason,created_by) VALUES(?,?,?,?)')->execute([$documentId,$type,$reason,$actor['id']]);foreach($items as$item){$pid=(string)($item['product_id']??'');$quantity=(int)($item['quantity']??-1);if($quantity>1000000||($type!=='adjustment'&&$quantity<=0)||($type==='adjustment'&&$quantity<0))throw new RuntimeException('VALIDATION_ERROR');$product=$this->one('SELECT * FROM pos_products WHERE id=? FOR SHARE',[$pid]);$cost=$this->one('SELECT fixed_cost FROM pos_product_costs WHERE product_id=? FOR SHARE',[$pid]);$balance=$this->one('SELECT * FROM pos_inventory_balances WHERE product_id=? FOR UPDATE',[$pid]);if(!$product||!$cost||!$balance)throw new RuntimeException('PRODUCT_NOT_FOUND');if($type==='opening'&&$this->one('SELECT id FROM pos_inventory_movements WHERE product_id=? LIMIT 1',[$pid]))throw new RuntimeException('OPENING_EXISTS');if($type==='adjustment'&&(int)$balance['version']!==(int)($item['stock_version']??0))throw new RuntimeException('VERSION_CONFLICT');$delta=$type==='adjustment'?$quantity-(int)$balance['on_hand']:(in_array($type,['issue','damage'],true)?-$quantity:$quantity);if($delta===0)continue;$purchase=$item['purchase_price']??null;if($type==='receipt'&&!preg_match('/^[0-9]{1,15}$/',(string)$purchase))throw new RuntimeException('VALIDATION_ERROR');$lineId=self::uuid();$this->pdo->prepare('INSERT INTO pos_inventory_document_items(id,document_id,product_id,quantity_delta,unit_purchase_price,fixed_cost_snapshot,sku_snapshot,name_snapshot) VALUES(?,?,?,?,?,?,?,?)')->execute([$lineId,$documentId,$pid,$delta,$purchase,$cost['fixed_cost'],$product['sku'],$product['name']]);$this->moveStock($pid,$delta,$type,$actor['id'],$lineId,null,null);}return['id'=>$documentId];
    }
    private function exchange(array$actor,array$p):array{$returnId=(string)($p['return_id']??'');if(!$this->one('SELECT id FROM pos_sales_returns WHERE id=? FOR UPDATE',[$returnId]))throw new RuntimeException('VALIDATION_ERROR');$order=$this->one('SELECT id FROM pos_sales_orders WHERE exchange_return_id=?',[$returnId]);if($order)return['id'=>$order['id']];$id=self::uuid();$this->pdo->prepare('INSERT INTO pos_sales_orders(id,created_by,exchange_return_id,note) VALUES(?,?,?,?)')->execute([$id,$actor['id'],$returnId,'Đổi hàng từ phiếu trả '.$returnId]);return['id'=>$id];}
    private function glassBrand(array$actor,array$p):array{$name=trim((string)($p['name']??''));if($name===''||mb_strlen($name)>100)throw new RuntimeException('VALIDATION_ERROR');$id=self::uuid();$this->pdo->prepare('INSERT INTO pos_glass_brands(id,name) VALUES(?,?)')->execute([$id,preg_replace('/\s+/u',' ',$name)]);return['id'=>$id];}
    private function staffState(array$actor,array$p):array{$id=(string)($p['id']??'');$user=$this->one("SELECT * FROM pos_users WHERE id=? AND role='staff' AND deleted_at IS NULL FOR UPDATE",[$id]);if(!$user)throw new RuntimeException('FORBIDDEN');$active=array_key_exists('active',$p)?(int)(bool)$p['active']:(int)$user['active'];$name=array_key_exists('display_name',$p)?trim((string)$p['display_name']):$user['display_name'];if($name===''||mb_strlen($name)>100)throw new RuntimeException('VALIDATION_ERROR');$this->pdo->prepare('UPDATE pos_users SET active=?,display_name=? WHERE id=?')->execute([$active,$name,$id]);if(!$active)$this->pdo->prepare('DELETE FROM pos_sessions WHERE user_id=?')->execute([$id]);return['id'=>$id];}
    private function moveStock(string$productId,int$quantity,string$type,string$actorId,?string$documentItem,?string$saleItem,?string$returnItem):void{$balance=$this->one('SELECT * FROM pos_inventory_balances WHERE product_id=? FOR UPDATE',[$productId]);if(!$balance||(int)$balance['on_hand']+$quantity<0)throw new RuntimeException('INSUFFICIENT_STOCK');$after=(int)$balance['on_hand']+$quantity;$version=(int)$balance['version']+1;$this->pdo->prepare('UPDATE pos_inventory_balances SET on_hand=?,version=? WHERE product_id=?')->execute([$after,$version,$productId]);$this->pdo->prepare('INSERT INTO pos_inventory_movements(id,product_id,movement_type,quantity_delta,balance_after,product_version_after,inventory_document_item_id,sale_order_item_id,return_item_id,actor_id) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([self::uuid(),$productId,$type,$quantity,$after,$version,$documentItem,$saleItem,$returnItem,$actorId]);}
    private function audit(string$actor,string$action,string$detail):void{$this->pdo->prepare('INSERT INTO pos_audit_logs(id,actor_id,action,detail) VALUES(?,?,?,?)')->execute([self::uuid(),$actor,$action,$detail]);}
    private function one(string$sql,array$values=[]):array|false{$s=$this->pdo->prepare($sql);$s->execute($values);return$s->fetch();}
    private function all(string$sql,array$values=[]):array{$s=$this->pdo->prepare($sql);$s->execute($values);return$s->fetchAll();}
    private function scalar(string$sql,array$values=[]):mixed{$s=$this->pdo->prepare($sql);$s->execute($values);return$s->fetchColumn();}
    private function canonical(mixed$value):string{if(is_array($value)){if(array_keys($value)!==range(0,count($value)-1))ksort($value);foreach($value as$key=>$item)$value[$key]=json_decode($this->canonical($item),true);}return json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
    public static function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
