<?php
declare(strict_types=1);

use App\Controllers\PageController;
use App\Controllers\ApiController;
use App\Controllers\AuthController;
use App\Controllers\AdminController;
use App\Controllers\AdminApiController;
use App\Controllers\PosController;

$pages = new PageController();
$router->get('/', fn() => $pages->home());
$router->get('/san-pham', fn() => $pages->products());
$router->get('/san-pham/{slug}', fn(array $params) => $pages->product($params));
$router->get('/dich-vu-oem', fn() => $pages->oem());
$router->get('/dai-ly-phan-phoi', fn() => $pages->distribution());
$router->get('/linh-vuc-hoat-dong', fn() => $pages->businessAreas());
$router->get('/gioi-thieu', fn() => $pages->about());
$router->get('/tin-tuc', fn() => $pages->news());
$router->get('/tin-tuc/{slug}', fn(array $params) => $pages->article($params));
$router->get('/lien-he', fn() => $pages->contact());
$router->get('/login', fn() => $pages->login());
$api = new ApiController();
$router->get('/api/glass-lookup', fn() => $api->lookup());
$router->get('/api/images/{id}', fn(array $params) => $api->image($params));
$router->post('/api/contact', fn() => $api->contact());
$auth = new AuthController();
$router->post('/api/auth/login', fn() => $auth->login());
$router->post('/api/auth/logout', fn() => $auth->logout());
$admin = new AdminController();
$router->get('/admin', fn() => $admin->index());
$router->get('/admin/glass-lookup', fn() => $admin->lookup());
$router->get('/admin/messages', fn() => $admin->messages());
$adminApi = new AdminApiController();
$router->get('/api/admin/products', fn() => $adminApi->products());
$router->post('/api/admin/products', fn() => $adminApi->saveProduct());
$router->put('/api/admin/products/{id}', fn(array $params) => $adminApi->saveProduct($params));
$router->delete('/api/admin/products/{id}', fn(array $params) => $adminApi->deleteProduct($params));
$router->post('/api/admin/images', fn() => $adminApi->upload());
$router->get('/api/admin/glass-lookup', fn() => $adminApi->lookup());
$router->post('/api/admin/glass-lookup', fn() => $adminApi->saveLookup());
$router->put('/api/admin/glass-lookup/{id}', fn(array $params) => $adminApi->saveLookup($params));
$router->delete('/api/admin/glass-lookup/{id}', fn(array $params) => $adminApi->deleteLookup($params));
$router->post('/api/admin/messages/{id}/send', fn(array $params) => $adminApi->resendMessage($params));
$router->get('/robots.txt', function(): void { header('Content-Type: text/plain; charset=utf-8');echo "User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /login\nSitemap: ".rtrim(\App\Core\Env::get('APP_URL','http://localhost'),'/')."/sitemap.xml\n"; });
$router->get('/sitemap.xml', function(): void { header('Content-Type: application/xml; charset=utf-8');$base=rtrim(\App\Core\Env::get('APP_URL','http://localhost'),'/');$site=require BASE_PATH.'/config/site.php';$pages=[['/','weekly','1.0'],['/gioi-thieu','monthly','0.7'],['/linh-vuc-hoat-dong','monthly','0.8'],['/san-pham','weekly','0.9'],['/dai-ly-phan-phoi','monthly','0.8'],['/tin-tuc','weekly','0.7'],['/lien-he','yearly','0.6']];foreach((new \App\Repositories\ProductRepository())->all()as$p)$pages[]=['/san-pham/'.$p['slug'],'monthly','0.8'];foreach($site['news']as$a)$pages[]=['/tin-tuc/'.$a['slug'],'monthly','0.6'];echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';foreach($pages as[$path,$frequency,$priority])echo'<url><loc>'.e($base.$path).'</loc><lastmod>'.date('Y-m-d').'</lastmod><changefreq>'.$frequency.'</changefreq><priority>'.$priority.'</priority></url>';echo'</urlset>'; });
$router->get('/api/cron/keep-alive', fn() => \App\Core\Response::json(['ok'=>true,'note'=>'MySQL hosting không cần chống ngủ đông.']));
$pos = new PosController();
$router->post('/api/app/v1/auth/login', fn() => $pos->login());
$router->post('/api/app/v1/auth/logout', fn() => $pos->logout());
$router->post('/api/app/v1/session/touch', fn() => $pos->touch());
$router->get('/api/app/v1/workspace', fn() => $pos->workspace());
$router->post('/api/app/v1/query', fn() => $pos->query());
$router->post('/api/app/v1/mutations', fn() => $pos->mutate());
$router->post('/api/app/v1/products/delete', fn() => $pos->deleteProduct());
$router->post('/api/app/v1/reports', fn() => $pos->report());
$router->post('/api/app/v1/staff', fn() => $pos->staff());
$router->post('/api/app/v1/images', fn() => $pos->uploadImage());
$router->get('/api/app/v1/images/{path}', fn(array $params) => $pos->image($params));
$router->delete('/api/app/v1/images/{path}', fn(array $params) => $pos->deleteImage($params));
