<footer class="bg-dark text-white">
  <div class="container-custom py-10 md:py-12"><div class="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4 lg:gap-12">
    <div><a href="/" class="mb-4 inline-block text-2xl font-bold">Oufeidun</a><p class="mb-6 text-sm leading-relaxed text-gray-400"><?= e($site['company']['description']) ?></p><div class="flex gap-3"><a href="https://zalo.me/<?= e($site['company']['phone_raw']) ?>" target="_blank" class="flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-xs font-bold">Zalo</a><a href="<?= e($site['company']['facebook']) ?>" target="_blank" class="flex h-10 items-center rounded-full bg-white/10 px-3 text-xs font-bold">Facebook</a><a href="<?= e($site['company']['tiktok']) ?>" target="_blank" class="flex h-10 items-center rounded-full bg-white/10 px-3 text-xs font-bold">TikTok</a></div></div>
    <div><h3 class="mb-4 text-lg font-semibold">Liên kết nhanh</h3><ul class="space-y-3"><?php foreach($site['navigation'] as $link): ?><li><a href="<?= e($link['href']) ?>" class="text-sm text-gray-400 hover:text-white"><?= e($link['label']) ?></a></li><?php endforeach; ?><li><a href="/login" class="text-sm text-gray-400 hover:text-white">Đăng nhập quản trị</a></li></ul></div>
    <div><h3 class="mb-4 text-lg font-semibold">Sản phẩm & Dịch vụ</h3><ul class="space-y-3"><li><a class="text-sm text-gray-400" href="/san-pham/kinh-cuong-luc-caballo-android">Caballo Android</a></li><li><a class="text-sm text-gray-400" href="/san-pham/kinh-cuong-luc-oufeidun">Caballo iPhone</a></li><li><a class="text-sm text-gray-400" href="/san-pham/kinh-cuong-luc-oufeidun-diamond">Diamond Curved Glass</a></li><li><a class="text-sm text-gray-400" href="/dich-vu-oem">Dịch vụ OEM</a></li></ul></div>
    <div><h3 class="mb-4 text-lg font-semibold">Thông tin liên hệ</h3><ul class="space-y-4"><li class="flex gap-3"><?= icon('map','mt-0.5 h-5 w-5 shrink-0 text-primary-500') ?><span class="text-sm text-gray-400"><?= e($site['company']['address']) ?></span></li><li class="flex gap-3"><?= icon('phone','h-5 w-5 text-primary-500') ?><a href="tel:<?= e($site['company']['phone_raw']) ?>" class="text-sm text-gray-400"><?= e($site['company']['phone']) ?></a></li><li class="flex gap-3"><?= icon('mail','h-5 w-5 text-primary-500') ?><a href="mailto:<?= e($site['company']['email']) ?>" class="text-sm text-gray-400"><?= e($site['company']['email']) ?></a></li></ul></div>
  </div></div>
  <div class="border-t border-white/10"><div class="container-custom py-6"><p class="text-sm text-gray-500">© <?= date('Y') ?> <?= e($site['company']['full_name']) ?>. Bảo lưu mọi quyền.</p></div></div>
</footer>

