<?php
$heroTitle='Giới thiệu';$heroDescription='Tìm hiểu về hành trình phát triển và những giá trị cốt lõi của Oufeidun.';require BASE_PATH.'/app/Views/partials/page-hero.php';
$values=[['Tầm nhìn','Phát triển thành đơn vị cung cấp kính cường lực điện thoại đáng tin cậy, phục vụ khách hàng và hệ thống đại lý trên toàn quốc.','from-primary-500 to-secondary-500'],['Sứ mệnh','Cung cấp giải pháp kính cường lực toàn diện, đồng hành cùng đối tác phát triển bền vững, nâng cao giá trị thương hiệu.','from-secondary-500 to-primary-700'],['Giá trị cốt lõi','Chất lượng - Uy tín - Đổi mới - Hợp tác. Chúng tôi đặt lợi ích khách hàng lên hàng đầu trong mọi hoạt động.','from-primary-700 to-primary-900']];
$strengths=[['Kiểm soát chất lượng','Theo dõi sản phẩm qua các công đoạn sản xuất và kiểm tra thành phẩm.'],['Phân phối toàn quốc','Đồng hành cùng hệ thống đại lý trên toàn quốc.'],['Phối hợp đơn hàng','Trao đổi tiến độ và phương án giao nhận theo từng đơn hàng.'],['Giải pháp phù hợp','Tư vấn dòng kính, form máy và phương án hợp tác theo nhu cầu.'],['Hỗ trợ đối tác','Đồng hành trong quá trình lựa chọn sản phẩm và triển khai đơn hàng.'],['Đổi mới liên tục','Không ngừng cải tiến công nghệ và nâng cao chất lượng.']];
$events=[['2016','Thành lập nhà máy sản xuất','Nhà máy được thành lập tại Trung Quốc, tập trung sản xuất kính cường lực điện thoại.'],['11+ năm','Kinh nghiệm sản xuất','Đội ngũ tích lũy kinh nghiệm và hợp tác với nhiều doanh nghiệp tại Việt Nam.'],['2026','Thành lập Oufeidun Việt Nam','Phục vụ khách hàng trong nước thuận tiện và minh bạch hơn.']];
?>
<section class="section-padding"><div class="container-custom grid items-center gap-8 lg:grid-cols-2 lg:gap-12"><div><p class="text-sm font-semibold text-primary-600">Oufeidun Việt Nam</p><h2 class="heading-2 mt-4 text-dark">Nền tảng sản xuất và phân phối kính cường lực</h2><p class="mt-5 text-lg leading-8 text-gray-600">Nhà máy sản xuất được thành lập tại Trung Quốc từ năm 2016. Đội ngũ có hơn 11 năm kinh nghiệm trong lĩnh vực kính cường lực điện thoại và đã hợp tác với nhiều doanh nghiệp lớn nhỏ tại Việt Nam.</p><p class="mt-4 leading-7 text-gray-600">Oufeidun Việt Nam được thành lập năm 2026 nhằm cung cấp sản phẩm chất lượng, minh bạch thông tin và giúp khách hàng trong nước tiếp cận nguồn hàng thuận tiện hơn.</p></div><div class="aspect-video overflow-hidden rounded-3xl bg-slate-950"><img src="/images/feedback-2026-09/product-overview.webp" alt="Ba dòng kính cường lực Oufeidun Caballo và Diamond Curved Glass" class="h-full w-full object-contain"></div></div></section>
<section class="section-padding"><div class="container-custom"><div class="mb-7 text-center"><span class="mb-4 inline-block rounded-full bg-primary-50 px-4 py-1.5 text-sm font-semibold text-primary-600">Giá trị cốt lõi</span><h2 class="heading-2 text-dark">Tầm nhìn & Sứ mệnh</h2></div><div class="grid gap-6 md:grid-cols-3"><?php foreach($values as $item): ?><article class="h-full rounded-3xl bg-white p-8 shadow-md transition duration-300 hover:shadow-xl"><div class="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br <?= e($item[2]) ?>"><?= icon('check','h-8 w-8 text-white') ?></div><h3 class="mb-3 text-xl font-bold text-dark"><?= e($item[0]) ?></h3><p class="leading-relaxed text-gray-600"><?= e($item[1]) ?></p></article><?php endforeach; ?></div></div></section>
<section class="section-padding bg-gray-50"><div class="container-custom"><div class="mb-7 text-center"><span class="mb-4 inline-block rounded-full bg-primary-50 px-4 py-1.5 text-sm font-semibold text-primary-600">Lịch sử phát triển</span><h2 class="heading-2 text-dark">Hành trình của chúng tôi</h2></div><div class="relative mx-auto max-w-3xl"><div class="absolute bottom-0 left-8 top-0 w-0.5 bg-primary-200 md:left-1/2 md:-translate-x-px"></div><?php foreach($events as $index=>$event): ?><article class="relative mb-6 flex items-start gap-6 <?= $index%2 ? 'md:flex-row-reverse' : 'md:flex-row' ?>"><div class="absolute left-8 z-10 mt-1.5 h-4 w-4 -translate-x-1/2 rounded-full border-4 border-white bg-primary-500 shadow md:left-1/2"></div><div class="ml-16 md:ml-0 md:w-1/2 <?= $index%2 ? 'md:pl-12' : 'md:pr-12 md:text-right' ?>"><span class="mb-2 inline-block rounded-full bg-primary-50 px-3 py-1 text-sm font-bold text-primary-600"><?= e($event[0]) ?></span><h3 class="mb-1 text-lg font-bold text-dark"><?= e($event[1]) ?></h3><p class="text-sm text-gray-600"><?= e($event[2]) ?></p></div></article><?php endforeach; ?></div></div></section>
<section class="section-padding"><div class="container-custom"><div class="mb-7 text-center"><span class="mb-4 inline-block rounded-full bg-primary-50 px-4 py-1.5 text-sm font-semibold text-primary-600">Thế mạnh</span><h2 class="heading-2 text-dark">Tại sao chọn Oufeidun?</h2></div><div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><?php foreach($strengths as $item): ?><article class="flex gap-4 rounded-2xl bg-gray-50 p-5 transition duration-300 hover:bg-white hover:shadow-md"><div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-primary-100"><?= icon('check','h-6 w-6 text-primary-600') ?></div><div><h3 class="mb-1 font-bold text-dark"><?= e($item[0]) ?></h3><p class="text-sm text-gray-600"><?= e($item[1]) ?></p></div></article><?php endforeach; ?></div></div></section>
