<?php
$heroTitle='Tin tức'; $heroDescription=''; $heroTag='p'; require BASE_PATH.'/app/Views/partials/page-hero.php';
$bodyById = [
 1=>['Caballo Android là dòng kính cường lực dành cho điện thoại Android. Thông tin trên bộ ảnh sản phẩm thể hiện độ cứng 9H và độ dày kính 0,33 mm.','Khi chọn sản phẩm, khách hàng nên cung cấp đúng hãng và model điện thoại để được tư vấn form kính phù hợp.'],
 2=>['Dòng Caballo cho iPhone được giới thiệu cho các phiên bản từ iPhone 6 đến iPhone 17. Bộ thông số sản phẩm thể hiện độ cứng 9H, kính dày 0,25 mm và lớp keo dày 0,38 mm.','Thiết kế cạnh cong 3D và lớp phủ nano hướng đến trải nghiệm vuốt chạm ổn định, đồng thời hạn chế bám dấu vân tay trên bề mặt.'],
 3=>['Bộ ảnh Caballo thể hiện các đặc điểm gồm độ cứng 9H, độ trong suốt cao và khả năng duy trì thao tác cảm ứng trên màn hình.','Lớp phủ nano hỗ trợ hạn chế mồ hôi, dầu vân tay và bụi bẩn. Hiệu quả sử dụng còn phụ thuộc vào việc chọn đúng form và thao tác dán kính.'],
 4=>['Diamond Curved Glass là dòng kính có thiết kế cạnh cong 3D, độ cứng 9H và độ dày 0,5 mm theo thông tin trên ảnh sản phẩm.','Phiên bản trong ảnh dành cho iPhone 17 Pro Max và có tính năng chống tĩnh điện ESD. Khách hàng nên xác nhận model trước khi đặt hàng.'],
 5=>['Trước khi chọn kính, cần xác định chính xác hãng, model và phiên bản điện thoại vì vị trí loa, camera và kích thước màn hình có thể khác nhau.','Ngoài form máy, người dùng có thể cân nhắc độ dày, thiết kế cạnh kính và lớp phủ bề mặt. Hệ thống đại lý Oufeidun hỗ trợ tư vấn sản phẩm phù hợp.'],
];
$paragraphs = $bodyById[$article['id']] ?? [$article['excerpt']];
$related = array_values(array_filter($articles, fn($item) => $item['slug'] !== $article['slug']));
?>
<article class="section-padding"><div class="container-custom max-w-4xl"><a href="/tin-tuc" class="inline-flex items-center gap-2 text-sm font-semibold text-primary-600"><?= icon('arrow-left','h-4 w-4') ?> Quay lại tin tức</a><header class="mt-7"><span class="rounded-full bg-primary-50 px-3 py-1 text-sm font-semibold text-primary-600"><?= e($article['category']) ?></span><h1 class="heading-2 mt-4"><?= e($article['title']) ?></h1><div class="mt-4 flex items-center gap-2 text-sm text-gray-400"><?= icon('calendar','h-4 w-4') ?><time><?= e(date('d/m/Y',strtotime($article['date']))) ?></time></div></header><div class="mt-8 aspect-video overflow-hidden rounded-3xl bg-slate-950"><img src="<?= e($article['image']) ?>" alt="<?= e($article['title']) ?>" class="h-full w-full object-contain"></div><div class="mt-9 text-lg leading-8 text-gray-700"><?php foreach($paragraphs as $index=>$paragraph): ?><p class="<?= $index?'mt-6':'text-xl font-medium leading-8 text-dark' ?>"><?= e($paragraph) ?></p><?php endforeach; ?></div><aside class="mt-10 rounded-3xl bg-primary-50 p-6 sm:p-8"><h2 class="text-xl font-bold">Cần tư vấn sản phẩm hoặc giải pháp OEM?</h2><p class="mt-2 text-gray-600">Đội ngũ Oufeidun sẵn sàng hỗ trợ lựa chọn sản phẩm và phương án phù hợp với nhu cầu của bạn.</p><a href="/lien-he" class="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary-500 px-5 py-3 font-semibold text-white"><?= icon('phone','h-4 w-4') ?> Liên hệ tư vấn</a></aside></div></article>
<section class="section-padding bg-slate-50"><div class="container-custom"><div class="mb-7 flex items-end justify-between gap-4"><div><p class="font-semibold text-primary-600">Đọc thêm</p><h2 class="heading-3 mt-2">Bài viết liên quan</h2></div><a href="/tin-tuc" class="font-semibold text-primary-600">Xem tất cả →</a></div><div class="grid gap-6 md:grid-cols-3"><?php foreach(array_slice($related,0,3) as $item): ?><a href="/tin-tuc/<?= e($item['slug']) ?>" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div class="aspect-video bg-slate-950"><img src="<?= e($item['image']) ?>" alt="<?= e($item['title']) ?>" class="h-full w-full object-contain"></div><div class="p-5"><span class="text-xs font-semibold text-primary-600"><?= e($item['category']) ?></span><h3 class="mt-2 font-bold"><?= e($item['title']) ?></h3><p class="mt-2 line-clamp-2 text-sm text-slate-600"><?= e($item['excerpt']) ?></p></div></a><?php endforeach; ?></div></div></section>
