<?php $site = require BASE_PATH . '/config/site.php'; $featured = array_values(array_filter($products, fn($p) => !empty($p['featured']))); ?>
<section id="tra-cuu-ma-kinh" class="relative isolate min-h-[820px] scroll-mt-20 overflow-hidden bg-[#020817] pb-12 pt-24 text-white sm:pb-16 sm:pt-28 lg:pt-32">
  <picture class="pointer-events-none absolute inset-0"><source media="(min-width:1024px)" srcset="/images/client-2026-09/hero-desktop.webp"><img src="/images/client-2026-09/hero-mobile.webp" alt="" class="absolute inset-0 h-full w-full object-cover object-center"></picture><div class="absolute inset-0 bg-slate-950/20"></div>
  <div class="container-custom relative z-10 grid items-center gap-8 lg:min-h-[490px] lg:grid-cols-[.9fr_1.1fr] lg:gap-12">
    <div class="max-w-2xl"><p class="mb-6 inline-flex rounded-full border border-white/25 bg-white/10 px-5 py-3 text-lg font-bold backdrop-blur-sm sm:text-xl">Kính cường lực Oufeidun</p><h1 class="text-4xl font-bold leading-[1.12] tracking-tight sm:text-5xl lg:text-6xl">Oufeidun - <span class="text-secondary-400">Chuẩn trên từng điểm chạm.</span></h1><p class="mt-7 max-w-xl text-lg leading-8 text-slate-200 sm:text-xl">Chuyên sản xuất OEM và phân phối kính cường lực Oufeidun chất lượng cao cho hệ thống đại lý toàn quốc.</p>
      <div class="mt-7 grid max-w-xl grid-cols-2 gap-2.5 sm:gap-3"><?php foreach([['5+','Năm kinh nghiệm'],['1.000+','Sản phẩm'],['Toàn quốc','Hệ thống phân phối'],['99%','Khách hàng hài lòng']] as $metric): ?><div class="rounded-2xl border border-amber-300/20 bg-white/[.07] px-4 py-3.5 shadow-lg backdrop-blur-sm"><strong class="block text-2xl font-bold leading-none text-secondary-300 sm:text-3xl"><?= e($metric[0]) ?></strong><span class="mt-2 block text-xs font-medium text-slate-300 sm:text-sm"><?= e($metric[1]) ?></span></div><?php endforeach; ?></div>
      <div class="mt-8 hidden flex-wrap gap-7 lg:flex"><a href="/san-pham" class="inline-flex items-center gap-2 font-semibold text-secondary-300">Xem danh mục sản phẩm <?= icon('arrow-right','h-4 w-4') ?></a><a href="/dich-vu-oem" class="inline-flex items-center gap-2 font-semibold text-white">Liên hệ OEM <?= icon('arrow-right','h-4 w-4') ?></a></div>
    </div>
    <div data-lookup class="relative min-w-0 rounded-[2rem] border border-white/15 bg-white p-5 text-dark shadow-2xl sm:p-7"><span class="inline-flex rounded-full bg-secondary-100 px-3 py-1.5 text-xs font-bold uppercase tracking-[.14em] text-secondary-800">Tra cứu nhanh</span><h2 class="mt-4 text-2xl font-bold sm:text-3xl">Tra cứu mã kính dùng chung</h2><p class="mt-3 text-sm leading-6 text-slate-600 sm:text-base">Nhập dòng điện thoại hoặc SKU để xem đúng mã kính và các máy có thể dùng chung.</p>
      <form class="mt-6"><div class="flex flex-col gap-3 sm:flex-row"><div class="relative flex-1"><?= icon('search','absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400') ?><input data-lookup-input maxlength="80" autocomplete="off" placeholder="VD: iPhone 15, Samsung A55..." class="w-full rounded-2xl border border-slate-300 bg-slate-50 py-4 pl-12 pr-4 outline-none focus:border-primary-500"></div><button type="submit" class="inline-flex items-center justify-center gap-2 rounded-2xl bg-secondary-500 px-6 py-4 font-bold text-slate-950">Tra cứu <?= icon('arrow-right','h-4 w-4') ?></button></div><p data-lookup-error hidden class="mt-2 text-sm font-medium text-red-600"></p></form>
      <div class="mt-5 flex flex-wrap items-center gap-2"><span class="text-xs font-medium text-slate-500">Tìm nhanh:</span><?php foreach(['iPhone 15','Samsung A55','OPPO A7'] as $example): ?><button type="button" data-lookup-example="<?= e($example) ?>" class="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600"><?= e($example) ?></button><?php endforeach; ?></div>
      <div data-lookup-panel hidden class="mt-5 border-t border-slate-200 pt-4 max-lg:hidden"><div data-lookup-summary class="mb-3"></div><div data-lookup-results class="lookup-scroll h-[162px] space-y-2.5 overflow-y-auto pr-2"></div></div>
    </div>
  </div>
</section>
<section class="section-padding bg-slate-50"><div class="container-custom grid items-center gap-8 lg:grid-cols-[.85fr_1.15fr] lg:gap-12"><div><p class="font-semibold text-primary-600">Về Oufeidun</p><h2 class="mt-4 text-3xl font-bold leading-tight sm:text-4xl">Sản xuất OEM &amp; phân phối kính cường lực điện thoại, cung cấp giải pháp nguồn hàng ổn định cho hệ thống đại lý, nhà bán lẻ và đối tác thương hiệu trên toàn quốc.</h2><p class="mt-5 text-lg leading-8 text-gray-600">Oufeidun tập trung vào kính cường lực Caballo: chuẩn form, độ trong suốt cao và cảm ứng ổn định cho Android và iPhone.</p><a href="/gioi-thieu" class="mt-6 inline-flex items-center gap-2 font-semibold text-primary-600">Tìm hiểu thêm <?= icon('arrow-right','h-4 w-4') ?></a></div><div class="grid grid-cols-2 gap-3 sm:gap-5"><?php foreach([['Kính cường lực Oufeidun','Dòng kính cường lực chủ lực','/san-pham','bg-[#081A38] text-white'],['Tra cứu các mã dùng chung','Tìm nhanh theo dòng máy hoặc SKU','/#tra-cuu-ma-kinh','bg-white text-dark ring-1 ring-amber-200'],['Chính sách đại lý toàn quốc','Hỗ trợ hệ thống phân phối','/dai-ly-phan-phoi','bg-primary-600 text-white'],['OEM','Sản xuất và gia công theo yêu cầu','/dich-vu-oem','bg-secondary-400 text-slate-950']] as $card): ?><a href="<?= e($card[2]) ?>" class="flex min-h-36 flex-col justify-between rounded-[1.5rem] p-4 shadow-sm sm:min-h-40 sm:p-6 <?= e($card[3]) ?>"><strong class="text-lg leading-tight sm:text-2xl"><?= e($card[0]) ?></strong><span class="mt-5 text-sm font-medium opacity-75"><?= e($card[1]) ?></span></a><?php endforeach; ?></div></div></section>
<section class="section-padding"><div class="container-custom"><div class="mb-7 text-center"><span class="font-semibold text-primary-600">Sản phẩm nổi bật</span><h2 class="heading-2 mt-2">Kính cường lực Oufeidun</h2><p class="mt-3 text-slate-600">Lựa chọn sản phẩm theo dòng máy, thông số và nhu cầu sử dụng.</p></div><div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3"><?php foreach($featured as $product) require BASE_PATH.'/app/Views/partials/product-card.php'; ?></div></div></section>
<section class="section-padding bg-slate-50"><div class="container-custom"><div class="grid gap-5 md:grid-cols-2"><?php foreach([['store','Thương mại & Phân phối','Cung cấp kính cường lực Caballo chất lượng cao cho hệ thống cửa hàng và đại lý.','/san-pham'],['factory','Sản xuất & Gia công OEM','Phát triển sản phẩm, thiết kế bao bì, in logo, sản xuất và đóng gói theo yêu cầu.','/dich-vu-oem']] as $service): ?><a href="<?= e($service[3]) ?>" class="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary-100 text-primary-600"><?= icon($service[0],'h-6 w-6') ?></div><h2 class="mt-5 text-2xl font-bold"><?= e($service[1]) ?></h2><p class="mt-3 leading-7 text-slate-600"><?= e($service[2]) ?></p><span class="mt-5 inline-flex items-center gap-2 font-semibold text-primary-600">Tìm hiểu thêm <?= icon('arrow-right','h-4 w-4') ?></span></a><?php endforeach; ?></div></div></section>
<section class="section-padding"><div class="container-custom"><div class="mx-auto mb-6 max-w-2xl text-center"><p class="font-semibold text-primary-600">Góc nhìn thực tế</p><h2 class="heading-2 mt-2">Bên trong nhà xưởng Oufeidun</h2><p class="mt-3 text-slate-600">Quan sát thiết bị, khu vực làm việc và chất lượng dây chuyền qua video thực tế tại nhà xưởng.</p></div><div class="mx-auto max-w-4xl overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-xl"><div class="bg-slate-950"><video controls playsinline preload="metadata" poster="/images/products/2026-09/ben-trong-nha-xuong-poster.webp" class="aspect-video w-full object-contain"><source src="/videos/2026-09/ben-trong-nha-xuong.mp4" type="video/mp4"></video></div><div class="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="text-lg font-bold">Không gian nhà xưởng</h3><p class="mt-1 text-sm text-slate-600">Hình ảnh thực tế về thiết bị và khu vực sản xuất.</p></div><a href="/dich-vu-oem#nang-luc-san-xuat" class="inline-flex items-center gap-2 text-sm font-semibold text-primary-600">Xem năng lực sản xuất <?= icon('arrow-right','h-4 w-4') ?></a></div></div></div></section>
<section class="section-padding bg-gray-50"><div class="container-custom"><div class="mb-7 flex items-end justify-between"><div><p class="font-semibold text-primary-600">Tin tức</p><h2 class="heading-2 mt-2">Thông tin mới nhất</h2></div><a href="/tin-tuc" class="hidden items-center gap-2 font-semibold text-primary-600 sm:flex">Xem tất cả <?= icon('arrow-right','h-4 w-4') ?></a></div><div class="grid gap-6 md:grid-cols-3"><?php foreach(array_slice($site['news'],0,3) as $article): ?><a href="/tin-tuc/<?= e($article['slug']) ?>" class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="aspect-video bg-slate-950"><img src="<?= e($article['image']) ?>" alt="<?= e($article['title']) ?>" class="h-full w-full object-contain"></div><div class="p-5"><span class="text-xs font-semibold text-primary-600"><?= e($article['category']) ?></span><h3 class="mt-2 font-bold"><?= e($article['title']) ?></h3><p class="mt-2 line-clamp-3 text-sm text-slate-600"><?= e($article['excerpt']) ?></p></div></a><?php endforeach; ?></div></div></section>
<section class="section-padding bg-primary-700 text-white"><div class="container-custom flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><h2 class="text-3xl font-bold">Sẵn sàng hợp tác cùng Oufeidun?</h2><p class="mt-2 text-white/80">Liên hệ để nhận tư vấn sản phẩm, chính sách đại lý hoặc giải pháp OEM.</p></div><a href="/lien-he" class="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3 font-semibold text-primary-700">Liên hệ ngay <?= icon('arrow-right','h-4 w-4') ?></a></div></section>
